# Generated by Django 4.1.1 on 2022-09-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='information')),
                ('link_name', models.URLField()),
                ('specialist', models.CharField(max_length=300)),
            ],
        ),
    ]
