# Generated by Django 4.1.1 on 2022-09-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='icon',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
