# Generated by Django 4.1.1 on 2022-09-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_information_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='information',
            name='link_name',
        ),
        migrations.RemoveField(
            model_name='information',
            name='specialist',
        ),
        migrations.AddField(
            model_name='information',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='information',
            name='phone_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='SpecialistInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=300)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.information')),
            ],
        ),
        migrations.CreateModel(
            name='IconInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.URLField()),
                ('icon', models.CharField(max_length=150)),
                ('font_color', models.CharField(choices=[('fac', 'fac'), ('twi', 'twi'), ('dri', 'dri'), ('ins', 'ins'), ('tel', 'tel')], max_length=150)),
                ('information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.information')),
            ],
        ),
    ]
