# Generated by Django 4.1.1 on 2022-09-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_information_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
